### ISSUE TITLE
Contact Email needs customising

### ISSUE THREAD

**Issue by Ressy66** [zonemaster/zonemaster#1013]
There needs to be an easy way to configure the contact email address on the main page, currently its seems hidden somewhere in the web GUI code.
This contact address should be for the local running server instance, not the master , zonemaster dot net, if they need to report bugs the github link is right next to it :)

(I know from first hand experience nobody replies to the default email anyway so its pointless having it point to where it does)

**Comment by matsduf** [comment]
@Ressy66, thank you for your feedback. Your request has already been met for the upcoming release planned for the end of November 2021. See https://github.com/zonemaster/zonemaster-gui/blob/develop/docs/Configuration.md for the documentation of the new configuration possibilities. Note that the link goes to the develop branch. It will be merged to the master branch at release. Any comments on the solution are welcome.

The mail address that we use returns an auto reply with instructions. If the link the auto reply is followed there is another email address that we do follow. The arrangement is not the best, but we were drowned by spam before and we had to do something.
