### ISSUE TITLE
No check for IPv6 only..?

### ISSUE THREAD

**Issue by kim-bjoern** [zonemaster/zonemaster#1037]
Thanks for a great tool! I've used it to streamline (and learn about) an authoritative setup.

One thing that puzzles me a bit in configuring a nameserver for PTR/rDNS; why doesn't the test report if the nameservers are IPv6 only, and/or only reachable via IPv6?

My nameservers (eventually) passed "with flying colours" - but failed to work, because they were IPv6 only.

My $0.02 - Kim Bjoern

**Comment by matsduf** [comment]
Thanks. That looks like a bug. Could you share what domain you tested? Either here or by email to me (see my profile).

**Comment by kim-bjoern** [comment]
> Thanks. That looks like a bug. Could you share what domain you tested? Either here or by email to me (see my profile).

5.0.1.b.4.0.0.4.6.0.a.2.ip6.arpa

Please note that I am currently working on the zone - adding/testing with IPv4's

**Comment by matsduf** [comment]
I see that https://zonemaster.dk-hostmaster.dk/ runs an older version of Zonemaster (Zonemaster-Engine v2.0.6). The issue has been fixed in later version and will not show up in https://zonemaster.net/result/3ebbdfb91bcd818c (Zonemaster-Engine v4.4.0).
