### ISSUE TITLE
Short support for an OS LTS version

### ISSUE THREAD

**Issue by repperille** [zonemaster/zonemaster#1125]
The project has apparently decided that: "Only the latest long-term supported version of Debian, FreeBSD and Ubuntu, respectively, is supported."

A standard support for an Ubuntu LST release is five years. Since there is an Ubuntu LTS version every second year (16.04, 18,04, 20,04, 22.04, ...) this has the effect that the Zonemaster project is only supporting the Ubuntu LTS for two years.

I think this is wrong. I wish that the Zonemaster project shall support the OS as long as the OS is supported.

br
Richard Persson

**Comment by matsduf** [comment]
If libldns3 is removed from the list of dependencies, Zonemaster::Engine can be installed on Ubuntu 20.04 using the CPAN method. PR https://github.com/zonemaster/zonemaster-engine/pull/1176 removes that library from the list of dependencies.

**Comment by matsduf** [comment]
Resolved by #1127
