### ISSUE TITLE
Translation: improve how a new language is created and added

### ISSUE THREAD

**Issue by pnax** [zonemaster/zonemaster#1131]
Currently, the [translation documentation](https://github.com/zonemaster/zonemaster/blob/master/docs/internal-documentation/maintenance/Instructions-for-translators.md) suggests to copy/paste an existing .po file to add a new language:

> Go to the share directory and use an existing PO file, say sv.po, and make a copy of that to the new file name. Update it and "add" it to git before working on it.

Doing so, all msgstr will be already populated. It would be nice to provide a cleaner way to create a new .po file.

Each components already have a `extract-pot` recipe. This POT file could be used when creating a new language.

Suggestions:
* update the documentation instruction using the `extract-pot` recipe
* create a new recipe that will create the new `xx.po` file for the new language

**Comment by matsduf** [comment]
A good suggestion. With an empty PO file it easier to see what is not translated.

**Comment by pnax** [comment]
Done with https://github.com/zonemaster/zonemaster-engine/pull/1185, https://github.com/zonemaster/zonemaster-cli/pull/304, https://github.com/zonemaster/zonemaster-backend/pull/1080 and https://github.com/zonemaster/zonemaster/pull/1135
