### ISSUE TITLE
Thoughts and suggestion on our git workflow

### ISSUE THREAD

**Issue by pnax** [zonemaster/zonemaster#1134]
From my understanding, our current git workflow is based on successive refinements performed across the years. Based on the discussions and questions I've asked and delving into the git history since I'm working on this project, this is what I've understood.

### Stage 0: everyone worked into master

At the beginning of the project, few people were involved. It was quite easy and common to directly work into _master_.

### Stage 1: let's use the merge request feature

To clarify and track changes, pull requests were used. This introduced the usage of external branches to conduct the work. Everyone still pushed its merge into _master_. Sometimes commits were made directly into _master_ without request.

### Stage 2: develop in "develop", release in "master"

At some point (in 2017) it was decided to conduct the work in a separate branch _develop_ that will be merged into _master_ at release time.

This allowed to always have a branch with a working state of the component that is pointing to its latest released version.

### Stage 3: how can we handle a revert?

> edit: this stage was not exactly the one encountered. In fact the problem encountered was that some merge requests were merged in _master_ instead of _develop_ and then reverted in _master_. See https://github.com/zonemaster/zonemaster/pull/1137#pullrequestreview-1279862975, https://github.com/zonemaster/zonemaster/pull/1137#issuecomment-1413433216 for a discussion and https://github.com/zonemaster/zonemaster/pull/1137#issuecomment-1422441811 for an explanation.

This was great until a release was done that was broken. A rollback occurred. This translates into a _revert_ in _master_. Then the work was fixed in _develop_ and merged into _master_. This is were something bad happened. Reverting a change in git can be tricky since it does remove the data but does not remove the associated commits from the history [[1],[2],[3],[4],[5]].

To avoid future issue when dealing with potential rollback (and revert), new steps were introduced during the release process. The main idea is to use an intermediate branch between _develop_ and _master_ at release time that glue those branch and history together. Hence reverting the merge between _merge-develop-into-master_ (the glue branch name) won't be a trouble when fixing the error and doing a new release.

As of [v2022.2][merge develop into master], these are the steps to perform this task:

```                                                        
git checkout -b merge-develop-into-master origin/develop
git reset --soft origin/master
git commit -m 'Update master to state of develop'
git merge origin/develop

# the next commands are the equivalent to the merge request
git checkout master
git merge --no-ff merge-develop-into-master
```

One drawback of this method is that the git history seen from the _master_ branch is hidden in one commit. Commands such as `git blame` will show their utility from the _develop_ branch.

### Stage 4: let's keep track of release waypoints

With the current workflow, the _develop_ branch is progressing on its own without knowledge of the release tag added into _master_. A command such as `git describe --tags` is of little interest then.

To solve this issue, it has been decided to merge back _master_ into _develop_, [see instructions as of v2022.2][merge master into develop]. This led to make the usage of commands like `git blame` trickier (if not useless, I have to admit I've not found how to bypass this merge with `git blame`).

### New stage: clarify everything learned so far and new suggestion

To summarize:

  * our current process relies on 2 branches: _master_ and _develop_
  * to avoid problem when a release needs to be rollbacked, an intermediary branch is used at release time: _merge-into-develop_
  * in order to keep track of the release points in _develop_, the _master_ branch should be merged into _develop_ after a release

When it comes to reverting a merge, the discussions in [[1],[2],[3],[4],[5]] make it clear that such revert should then be re-reverted before applying the fix.

Could we consider dropping the need of the extra branch at release time? I see several gains:

  * ease the release process by avoiding the burden of an extra branch and associated merge request
  * avoid burying the git history behind intermediary merges

The major drawback could be to remember to revert the revert in case of a release rollback (which should be a very seldom event). This could be documented in our release process documents, for instance in the [ReleaseProcess-release] document.

[1]: https://github.com/git/git/blob/master/Documentation/howto/revert-a-faulty-merge.txt
[2]: https://www.spinics.net/lists/git/msg87780.html
[3]: https://www.spinics.net/lists/git/msg87783.html
[4]: https://www.spinics.net/lists/git/msg87788.html
[5]: https://www.spinics.net/lists/git/msg87795.html
[merge develop into master]: https://github.com/zonemaster/zonemaster/blob/v2022.2/docs/internal-documentation/maintenance/ReleaseProcess-release.md#14-merge-develop-branch-into-master
[merge master into develop]: https://github.com/zonemaster/zonemaster/blob/v2022.2/docs/internal-documentation/maintenance/ReleaseProcess-release.md#18-merge-master-into-develop
[ReleaseProcess-release]: https://github.com/zonemaster/zonemaster/blob/master/docs/internal-documentation/maintenance/ReleaseProcess-release.md

**Comment by matsduf** [comment]
Which merging creates the problem, 1 or 2?
1. Merging develop into master via merge-develop-into-master as one commit?
2. Merging master into develop?

If we keep (1) but skip (2) we handle the reverting situations as today. What we will not get in develop branch are some merge commits and the tag. I think we can live without the merge commits, can't we?

I think the issue with the tag could be solved by creating the tag on the develop branch just before doing (1).

If you think that would solve the issue, then we could test it on a separate test repository.

Or how do you think the release instructions should look like?

**Comment by matsduf** [comment]
> If we keep only (1), this would be ok. If we want to do (2) as well, then (1) is problematic. 

My suggestion was (is):
1. Set the release tag in develop branch just before the next step
2. Merging develop into master via merge-develop-into-master
3. Do not merge master into develop

It should be tested first.

> My suggestion on this is that we could have:
> 
> 1bis. Merging develop into master 
> 2. Merging master into develop
> 
> I'll provide a suggestion on how the release instructions would look like then.

Please do. We did that before but had problems with reverts.

**Comment by pnax** [comment]
> 1. Set the release tag in develop branch just before the next step

I don't think this would be a good idea to tag on develop instead of master. This feels more natural to tag the commit related to the release.

> Please do.

See https://github.com/zonemaster/zonemaster/pull/1137

**Comment by pnax** [comment]
Improved with #1137
