### ISSUE TITLE
Make job_status report proper percentages

### ISSUE THREAD

**Issue by mattias-p** [zonemaster/zonemaster#1176]
Update `job_status` to report the closest integer percentage of test cases completed instead of the weird pseudo-percentage used by `test_progress`.

We could support both at the same time by:
1. having the database store progress in the range 0&ndash;9900 inclusive,
2. having `job_status` return `n / 99`, and
3. having `test_progress` return `if created { 0 } else if running { max(1, n/100) } else { 100 }`.

#### Alternatives
* We could let `job_status` round its percentage to the closest integer instead of always rounding down.
* We could let `job_status` keep reporting weird pseudo-percentages until we remove `test_progress`, and then update `job_status` to report proper percentages.
* We could leave `job_status` as is and let the meaning of the `progress percentage` remain vague.
* We could leave `job_status` as is and just document its progress values in all their weridness.

## Stabilization
[Tracking issue](https://github.com/zonemaster/zonemaster/issues/1175)

### Affected interfaces
Compatibly changed:
* job_status

### Dependencies
* This proposal depends on zonemaster/zonemaster-backend#960.

### Overlapping proposals
None

**Comment by matsduf** [comment]
I do not see the problem with today's solution where 1-99% used to indicate the progress.

**Comment by matsduf** [comment]
There are two purposes of "progress", one is to encode the state of the test. The other is provide the data for the progress bar on GUI. For the latter it is not important that it gives an exact percentage figure. It is OK if it is quite rough. It should preferably not go backwards.

Breaking out the state from progress would be good. After that, progress could be used as it is.

**Comment by mattias-p** [comment]
Solved by #1150.
