### ISSUE TITLE
IP-prefix diversity warning

### ISSUE THREAD

**Issue by pos42** [zonemaster/zonemaster#1221]
Hi

A suggestion in behavior change…

I think it would be better and more clear information if zonemaster changed the behavior of how warnings are handled for “IP Prefix Diversity”

Example. Let us say you have the following servers for your domain
NS1
NS2
NS3
NS4

Now, lets say NS1 and NS2 are within the same IP prefix, whereas NS3 and NS4 are in different IP prefixes. I.e you have tree different IP prefix:es spread over your four DNS servers.

In the above case zone master give an orange warning about NS1 and NS2 even though there is no availability risk at all if for example any of the IP-prefix:es used disappears from the internet routing table.

My point here is that:
1. I think zone master in this case should give an info notice only (yes, the user must of course be notified).
2. But zonemaster should only give an orange warning if all servers are in the same IP prefix.

Or is it reasonable to have an orange warning when there is no issue at all if any of the IP-prefixes are lost from routing? I think not…

Tnx
//Peo

**Comment by pos42** [comment]
Ahhh. I can see it has been logged before, but under a different heading :)

**Comment by matsduf** [comment]
@pos42, thank you for raising the issue. It is on our list, but not yet handled. I will close this issue since #1174 already covers the issue.
