### ISSUE TITLE
ZONE11 SPF policy validation on Reverse zone

### ISSUE THREAD

**Issue by cloudkuba** [zonemaster/zonemaster#1288]
Hi,

I'm testing my reverse DNS zone (b.c.d.in-addr.arpa) and I get an error when testing Zone11:

 None of the zone's name servers responded with an authoritative response to queries for SPF policies.

I don't understand this error, what exact DNS query is performed to obtain the SPF record? What is the point of this check in the case of a reverse DNS zone?

**Comment by matsduf** [comment]
There are two parts in your issue. One is if it is relevant to require SPF records in a reverse zone. Maybe not, and see #1256.

The other is if Zonemaster should warn if the response, as it seems, is non-authoritative. It would be strange with an non-authoritative response from an authoritative server for the zone. Before I can give a definite answer on this I would like to look at the Zonemaster test in question.

Would it be possible to share the zone name or the link to the zonemaster test? Either here as a comment to this issue (preferred) or in an email to me. 

You will find my email in my Github profile (@matsduf). If you send it directly to me I will only share it with my co-workers from Internetstiftelsen and Afnic.

**Comment by cloudkuba** [comment]
@matsduf Hi, thanks for your reply, I have sent the details in an e-mail.

**Comment by cloudkuba** [comment]
Problem solved, it was on my side.
