### ISSUE TITLE
New DNSSEC requirement: Check for DNSKEY algorithms

### ISSUE THREAD

**Issue by pawal** [zonemaster/zonemaster#231]
If there are DNSKEY keys in the zone with multiple algorithms, all algorithms must have corresponding RRSIG signatures in the zone.

This is covered in [Section 2.2 of RFC 4035](https://tools.ietf.org/html/rfc4035#section-2.2).

**Comment by cdybedahl** [comment]
You would't happen to know of a zone that does use multiple algorithms?

**Comment by pawal** [comment]
Perhaps @jschlyter is running a zone with multiple DNSKEY algorithms??

**Comment by jschlyter** [comment]
nxdomain.se is now signed with both RSA/SHA-256 and RSA/SHA-512. DS only for the RSA/SHA-256 at the moment, but I can add it if required.

**Comment by sandoche2k** [comment]
@pawal who shall we assign for this issue?

**Comment by pawal** [comment]
For test specification, I can do it. Implementation would be @vlevigneron when I am done with the spec.

**Comment by sandoche2k** [comment]
Thanks

**Comment by sandoche2k** [comment]
@pawal if possible, can you look at the test spec and finish when @calle is here

**Comment by sandoche2k** [comment]
@pawal Vincent told me that he could implement it (maybe before monday) if the test specifications are written. Can you have a look at this issue?

**Comment by sandoche2k** [comment]
@pawal - Can you have a look?

**Comment by sandoche2k** [comment]
VLE - Implements 
PWA - Write Test spec
Close the issue once both are done

**Comment by matsduf** [comment]
Make a suggestion of a specification for this issue. @pawal will give an oral overview.

**Comment by sandoche2k** [comment]
Specifications are not ready yet. Moving to 2017.1

**Comment by matsduf** [comment]
This issue will be solved bey #780.

**Comment by matsduf** [comment]
Resolved by #780.
