### ISSUE TITLE
Test suite, as a deliberately broken set of DNS zones

### ISSUE THREAD

**Issue by pawal** [zonemaster/zonemaster#320]
This issue was also documented in the [WishList for Version 2.0](https://github.com/dotse/zonemaster/blob/master/docs/requirements/WishList.md).

Test suite, as a deliberately broken set of DNS zones, like DNSSEC people did http://www.dnssec-tools.org/testzone/ .

**Comment by pawal** [comment]
Write a suggestion to the community.

**Comment by matsduf** [comment]
We are working on this in a separate project.
