### ISSUE TITLE
Test for DLV

### ISSUE THREAD

**Issue by pawal** [zonemaster/zonemaster#377]
Zonemaster should look for an entry in the DLV, and warn if found.

**Comment by pawal** [comment]
(This was also on request from an audience member at DNS-OARC.)

**Comment by sandoche2k** [comment]
@pawal pls. assign to @vlevigneron and mark this for release 2015.4

**Comment by matsduf** [comment]
On https://dlv.isc.org/ is says

```
In 2016, we plan to stop accepting zones that could validate to the Root, and will remove from the DLV any zones that already do. We will remove all records from DLV in 2017, but leave the (empty) service running. 
```

**Comment by matsduf** [comment]
Close this issue since it has been in the "icebox" for years.
