### ISSUE TITLE
Test all 3 components with each pull request of any of them

### ISSUE THREAD

**Issue by mtoma** [zonemaster/zonemaster#416]
Test all 3 components (engine, backend, gui) with each pull request of any of them

**Comment by sandoche2k** [comment]
@mtoma what do you want here? 
Do you have an assignee?

**Comment by mtoma** [comment]
The idea here was to trigger the travis tests for all 3 components whit each commit of any of the 3 components. (to avoid having ARAY() strings in the test results after the engine was modified without checking impacts on the GUI)
Is this the case?

Anyone can do this.

**Comment by mtoma** [comment]
What is needed:
http://eng.rightscale.com/2015/04/27/dependent-builds-in-travis.html

**Comment by pawal** [comment]
> On 03 Dec 2015, at 10:21, Michal TOMA <notifications@github.com> wrote:
> 
> What is needed:
> http://eng.rightscale.com/2015/04/27/dependent-builds-in-travis.html

But do we really want to test the GUI when we commit to the Engine?

**Comment by mtoma** [comment]
I don't see any other way to catch regressions like the ARRAY strings appearing in the GUI output than to trigger a travis test for the GUI.
This doesn't need to be blocking the engine commit like a standard travis test does but getting a warning e-mail that a commit to the engine broke something in the GUI or Backend the same day than the engine commit is done would really be nice.
As it seems TravisCI doesn't have this possibility as of now this will probably be completely replaced by the continuous automated testing environment that we need anyway.
I should have something ready in the newt 2 or 3 weeks.

**Comment by matsduf** [comment]
F2F: Now or never!

**Comment by matsduf** [comment]
Vill not fix.
