### ISSUE TITLE
Testing GOST, one day

### ISSUE THREAD

**Issue by bortzmeyer** [zonemaster/zonemaster#457]
Today, Zonemaster does not support GOST ([this test](https://www.zonemaster.net/test/8c0fc681bfe089ac) shows "Signature verification for DNSKEY with tag 17892 failed with error 'no GOST support'. ")

May be it could be nice in the future (a [recent survey](https://labs.ripe.net/Members/maciej_andzinski_2/support-for-elliptic-curve-cryptography-ecc-in-dns-resolvers-as-seen-by-ripe-atlas) indicates that GOST is not common in resolvers).

**Comment by matsduf** [comment]
GOST is not relevant for DNSSEC anymore ([RFC 8624]). Will not fix.

[RFC 8624]: https://www.rfc-editor.org/rfc/rfc8624.html
