### ISSUE TITLE
"NSEC3 record does not cover xx--example..." when there is no signatures

### ISSUE THREAD

**Issue by bortzmeyer** [zonemaster/zonemaster#458]
The zone renater.fr was broken ([test on DNSviz](http://dnsviz.net/d/renater.fr/Vwo7uA/dnssec/) because the name servers sent no signature at all. Zonemaster does not diagnose properly the problem ([test on ZoneMaster](https://zonemaster.net/test/90601d0afc1fd161). It sends a strange error message ("NSEC3
record does not cover xx--example.renater.fr") and it is just a warning (resolvers, of course, replied SERVFAIL).

**Comment by matsduf** [comment]
Cannot be reproduced.
