### ISSUE TITLE
DANE verification for the web

### ISSUE THREAD

**Issue by sandoche2k** [zonemaster/zonemaster#460]
Add TLSA check for port 443 (web) as 3rd party plugin

**Comment by bortzmeyer** [comment]
This requires doing a HTTP connection (with issues like timeout, etc). Is it something we want to do?

**Comment by pawal** [comment]
Not included in the main distribution, bus as Sandoche mentioned, as a third party plugin. This will also allow us to test the plugin framework, something that we have not really done.

**Comment by pawal** [comment]
However, we don't actually have to validate the TLSA record. But if added as a plugin, why not.

**Comment by tobbe-eklov** [comment]
There are utilities for this already

ex. 

ldns-dane verify www.interlan.se 443
192.71.21.47 dane-validated successfully
2001:67c:2448:10::47 dane-validated successfully

**Comment by matsduf** [comment]
@sandoche2k, I think it is out of scope of Zonemaster.

**Comment by matsduf** [comment]
F2F: out of scope.
