### ISSUE TITLE
Split BASIC02 into two test cases

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster#492]
Split BASIC02 into two test cases, one checking for existing delegation and one for checking if any nameserver is reachable.

See https://github.com/dotse/zonemaster-engine/issues/259

**Comment by vlevigneron** [comment]
@matsduf @sandoche2k Do you have a chedule for this TC specifications ?

**Comment by vlevigneron** [comment]
@matsduf @sandoche2k Any news about this TC specifications ?

**Comment by matsduf** [comment]
The test case will not be split. Basic02 will be updated by #1085.
