### ISSUE TITLE
Review the descriptions of all the methods in the specification and spot all differences between descriptions and the implementation of those methods

### ISSUE THREAD

**Issue by mtoma** [zonemaster/zonemaster#493]
It seems the matching between the descriptions of the methods and the implementation is not precise enough. 
As a consequence we end up with specifications that are impossible to implement.
Several solutions are possible but as a prerequisite we must find out all methods where descriptions do not match with implementation.
The purpose of this issue is to spot all of those methods.

**Comment by matsduf** [comment]
This is specifically about https://github.com/dotse/zonemaster/blob/master/docs/specifications/tests/Methods.md

**Comment by sandoche2k** [comment]
@matsduf before starting with the test case, i think we should rewrite the methods. As it is assigned to you, please make an initial draft, so that i can also start working on it.

**Comment by matsduf** [comment]
@mattias-p and I are working on it.

**Comment by matsduf** [comment]
New versions of the methods have been created by #656. See [MethodsNT].

[MethodsNT]: https://github.com/zonemaster/zonemaster/blob/master/docs/specifications/tests/MethodsNT.md
