### ISSUE TITLE
Subtle NSEC3 error undetected

### ISSUE THREAD

**Issue by bortzmeyer** [zonemaster/zonemaster#496]
.VN just created a new example of the traps of NSEC3. See DNSviz report: http://dnsviz.net/d/com.vn/WGn3nw/dnssec/

But Zonemaster does not detect this problem. https://zonemaster.net/test/e662cee67b98efd0

**Comment by sandoche2k** [comment]
Investigate the issue  to check whether it needs a change in the spec

**Comment by sandoche2k** [comment]
@bortzmeyer we are not able to get to the origin of the issue due to non availability of history in dnsviz. We will close it for now and we will reopen or create a new issue when we find the same issue again.
