### ISSUE TITLE
Create documentation of config/policy/profile

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster#498]
There is a need of documentation of format and place of config, policy and profile. Engine uses the config and policy, but can be selected by CLI. Backend can select policy (but called "profile" in API). GUI can also expose a selection of policies (called "profiles").

A work has been started to unify these files and to make config selectable in Backend API.

Since config and policy are shared across Engine, CLI and Backend, documentation is needed here, with references from Engine, CLI and Backend.

**Comment by matsduf** [comment]
We have decided to merge config and policy into a profile.

**Comment by mattias-p** [comment]
There is a WIP at https://github.com/dotse/zonemaster/tree/profiles

**Comment by sandoche2k** [comment]
@matsduf closed?

**Comment by sandoche2k** [comment]
@mattias-p close?
