### ISSUE TITLE
Use cpan for all installations of all components

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster#524]
When we do installations during testing we have to use cpan. It seems like cpan and cpanm have different behavior. We would get a consistency if we only support installation with cpan and do all test installations with cpan.

**Comment by mattias-p** [comment]
Actually, we don't have to choose `cpan`. `cpanm` is also a viable choice. But we do need to use the same tool when testing as is prescribed by the installation instruction.

**Comment by sandoche2k** [comment]
Yes. i agree. I have tested CentOS with CPANM. I will do the same with
Debian.

**Comment by matsduf** [comment]
I think we should update the installation instructions first.

**Comment by sandoche2k** [comment]
How does one update the installation instructions unless and otherwise we test it?  In the instructions document, the file that is installed is from the cpan portal.

To my understanding, we use cpanm while testing. If everything works, we push all ZM modules to PAUSE. Then test it via cpanm. If everything works, update the install instructions and make the release.

**Comment by mattias-p** [comment]
I view updating the installation instructions as a development effort. If I come across something that needs to be changed in the instruction during installation testing, I take off my installation tester hat and put on my developer hat. Then I make a PR to the develop branch with the changes. If the PR is accepted and merged, I expect that all installation testers to redo their testing, at least from the point of the first substantial change. Then i take off my developer hat and put on my installation tester hat again.

**Comment by sandoche2k** [comment]
I have paused my testing to have a clear and simple response from both @matsduf and @mattias-p. For testing currently before release, do i test with cpan or cpanm? 
I am ready to accept either even though currently i have a preference for cpanm, since i can see the advantages for testing multiple times on Debian and Centos with both.

**Comment by matsduf** [comment]
@sandoche2k, I can hear that both you and @mattias-p are in favor of cpanm() and therefore I cast my vote on cpanm() too. But the installation instructions must then be updated to include both how to install cpanm() and also cpanm() used for all cpan installations.

**Comment by sandoche2k** [comment]
Thanks. 
So.. do you agree with this process: 
1. Use "cpanm" while testing the locally created distrib file after running "make dist"
2. Document the installation process under internal documentation/distrib testing directory
2. After successful testing, push all ZM modules to PAUSE. 
3. Test again via cpanm the modules uploaded to cpanm mirrors. 
4. If everything works, update the install instructions 
5. make the release.

**Comment by matsduf** [comment]
We cannot upload to CPAN before release because then everybody will use those packages. My experience is that the difference between `cpanm Zonemaster::LDNS` and `cpanm Zonemaster-LDNS-1.0.2.tar.gz` is minute or even neglectable. I think we should have the following steps:

1. Update the internal instructions for creating distribution packages (but not replicating what is already written in [ReleaseProcess]) and merge to develop branch.
2. Update the the public instructions and merge to to develop branch.
3. Create dist packages using the instructions from the develop branch.
4. Test installation using the public installation instruction from the develop branch, but replacing `cpanm Zonemaster::*` with `cpanm Zonemaster-*.tar.gz`
5. If everything works, make a release and merge develop to master.
6. Test using the public installation instructions, but this time by installing from real CPAN.

[ReleaseProcess]: https://github.com/dotse/zonemaster/blob/master/docs/internal-documentation/maintenance/ReleaseProcess.md

**Comment by sandoche2k** [comment]
I agree

**Comment by sandoche2k** [comment]
we are using cpanm now
