### ISSUE TITLE
Test that the zone is signed with each algorithm in the DNSKEY RRset

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster#529]
From RFC 6840:

>       The DS RRset and DNSKEY RRset are used to signal which algorithms
>       are used to sign a zone.  The presence of an algorithm in either a
>       zone's DS or DNSKEY RRset signals that that algorithm is used to
>       sign the entire zone.
> 
>       A signed zone MUST include a DNSKEY for each algorithm present in
>       the zone's DS RRset and expected trust anchors for the zone.  The
>       zone MUST also be signed with each algorithm (though not each key)
>       present in the DNSKEY RRset.  It is possible to add algorithms at
>       the DNSKEY that aren't in the DS record, but not vice versa.  If
>       more than one key of the same algorithm is in the DNSKEY RRset, it
>       is sufficient to sign each RRset with any subset of these DNSKEYs.
>       It is acceptable to sign some RRsets with one subset of keys (or
>       key) and other RRsets with a different subset, so long as at least
>       one DNSKEY of each algorithm is used to sign each RRset.
>       Likewise, if there are DS records for multiple keys of the same
>       algorithm, any subset of those may appear in the DNSKEY RRset.

Create a test case that requires that the SOA RRset, the apex NS RRset and the DNSKEY RRset are signed with all algorithms present in the apex DNSKEY RRset.

**Comment by pawal** [comment]
Also see #344

**Comment by matsduf** [comment]
Replaced #527

**Comment by bortzmeyer** [comment]
Why just "the SOA RRset, the apex NS RRset and the DNSKEY RRset"? The RFC says "The zone MUST also be signed with each algorithm" where "the zone" is vague: is it all records or only the apex records (which may include other RR types)?

(RFC 4035 was clearer, saying that "each RRset" has to be signed with all algorithms.)

**Comment by matsduf** [comment]
We could include all RRsets in the apex, but besides that we do not know more names. If the zone is a NSEC zone, it would be possible to traverse the entire zone, but I am not sure if that is a good idea.

**Comment by bortzmeyer** [comment]
@matsduf Fair enough, I get it.

**Comment by matsduf** [comment]
PR #780 is meant to solve this issue.

**Comment by matsduf** [comment]
Resolved by PR #780.
