### ISSUE TITLE
Create N/A as severity level?

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster#538]
All messages from Engine is connected to a severity level: CRITICAL, ERROR, WARNING, NOTICE, INFO or DEBUG ([ConfigAndPolicy.pod](https://github.com/dotse/zonemaster-engine/blob/master/docs/ConfigAndPolicy.pod)).  How should we treat absence of DNSSEC? In DNS, DNSSEC is optional, and today the message that there is no DNSSEC is set as NOTICE, which is displayed as green, i.e. displayed as no error. It could give the impression that DNSSEC is up with no problem.

Should we introduce a psuedo-level "NA" to be displayed in grey in the GUI when there is no DNSSEC?

See https://github.com/dotse/zonemaster-gui/issues/155

**Comment by pawal** [comment]
Isn't this purely a usability issue?
There is also the option to add scoring for what makes "the internet better" (for some value of better), where a higher score indicates fully working IPv6 and DNSSEC, and such features that is not important to DNS itself.
