### ISSUE TITLE
Checking at least a part of the DNSSEC delegation?

### ISSUE THREAD

**Issue by bortzmeyer** [zonemaster/zonemaster#544]
When the domain is unsigned, Zonemaster reports it DNSSEC-OK (for instance https://zonemaster.net/test/9506e697b286faf0) even if the DNSSEC delegation from the parent is broken (which is the case here  http://dnsviz.net/d/museodelprado.es/WkyrvA/dnssec/) 

Could it be a good idea to test the delegation?

**Comment by matsduf** [comment]
There is currently no test case for the consistency of the parent zone. It could make sense to include some tests, but there is no natural limit until the entire path is checked, just as DNSVIZ does.

Please suggest what the new test cases should test.

**Comment by matsduf** [comment]
Cannot reproduce.
