### ISSUE TITLE
Migrate from "Changes" to "Changes.md"

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster#551]
~We extensively refer to issues and PRs in the Changes files in all repositories. To follow those the reader has to manually search for the issue or PR. If we make those files into md files, then we can create hyper-links. Migrate from "Changes" to "Changes.md" in all repositories. If needed, the "Changes" file could be kept with a reference to "Changes.md".~

Keep Changes as-is, but instead make the Github contain the entire section from the Changes file and in that create links.

The release process document will need to be updated.

**Comment by mattias-p** [comment]
I like the idea. However I found this https://metacpan.org/pod/distribution/CPAN-Changes/lib/CPAN/Changes/Spec.pod.

**Comment by pawal** [comment]
Yes, you do not want to change the current name or layout if you need your modules in CPAN.

**Comment by matsduf** [comment]
So there are pros and cons. We could have a reduced "Changes" in correct format with pointer to "Changes.md" in the package and at Github. We should not take any decision now.

**Comment by sandoche2k** [comment]
@matsduf so what is the decision? Do we need multiple Changes file?

**Comment by sandoche2k** [comment]
@matsduf can we take a decision and close this issue for 2019.1?

**Comment by matsduf** [comment]
See PR #750

**Comment by sandoche2k** [comment]
@matsduf close?

**Comment by matsduf** [comment]
Solved #570.
