### ISSUE TITLE
Strange "Cannot determine if the following servers are recursive nameservers or not"

### ISSUE THREAD

**Issue by bortzmeyer** [zonemaster/zonemaster#558]
https://zonemaster.net/test/ec3beec07e139fc0 : 

Cannot determine if the following servers are recursive nameservers or not: . 

What does it mean? Which name server and why is it impossible to determine if there is a RA bit?

**Comment by sandoche2k** [comment]
@matsduf will update the message

**Comment by matsduf** [comment]
The current version (v2019.1) does not emit such message.
