### ISSUE TITLE
Replies to AAAA or not?

### ISSUE THREAD

**Issue by bortzmeyer** [zonemaster/zonemaster#559]
https://zonemaster.net/test/ec3beec07e139fc0

Nameserver ns.icodia.com/46.31.192.40 dropped AAAA query.
Nameserver ns2.icodia.com/46.31.192.41 dropped AAAA query.
Nameserver ns3.icodia.com/176.162.151.73 dropped AAAA query.
The following nameservers answer AAAA queries without problems : ns3.icodia.com/176.162.151.73, ns.icodia.com/46.31.192.40, ns2.icodia.com/46.31.192.41. 

So, they reply or they do not reply? (According to dig, they reply.)

**Comment by matsduf** [comment]
@bortzmeyer, that is a good question. I will investigate further when I have proper IPv6 connection.

**Comment by matsduf** [comment]
> So, they reply or they do not reply? (According to dig, they reply.)

According to Zonemaster, they did not reply on the AAAA queries. Today it is an ERROR not a NOTICE by default

When I test today I sometimes get that result. When queried for names that the servers do not have, I get no answer:
```
   0.00 INFO      Using version v3.0.3 of the Zonemaster engine.
  12.58 WARNING   No response from ns2.icodia.com/46.31.192.41 asking for xn--nameservertest.iis.se.
  22.59 WARNING   No response from ns2.icodia.com/46.31.192.41 asking for xn--nameservertest.icann.org.
  32.62 WARNING   No response from ns2.icodia.com/46.31.192.41 asking for xn--nameservertest.ripe.net.
  42.64 WARNING   No response from ns3.icodia.com/176.162.151.73 asking for xn--nameservertest.iis.se.
  52.66 WARNING   No response from ns3.icodia.com/176.162.151.73 asking for xn--nameservertest.icann.org.
  62.68 WARNING   No response from ns3.icodia.com/176.162.151.73 asking for xn--nameservertest.ripe.net.
  72.70 WARNING   No response from ns.icodia.com/46.31.192.40 asking for xn--nameservertest.iis.se.
  82.72 WARNING   No response from ns.icodia.com/46.31.192.40 asking for xn--nameservertest.icann.org.
  92.75 WARNING   No response from ns.icodia.com/46.31.192.40 asking for xn--nameservertest.ripe.net.
```
