### ISSUE TITLE
TestMessages.md not updated

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster#569]
The file TestMessages.md lists all messages that can be emitted "from the test cases", but it has not been updated. It should be considered to be the authoritative source, not the code.

* Consider moving the information into the test case specifications.
* Consider adding the default level (debug, info etc) to the messages as the authoritative source.

https://github.com/dotse/zonemaster/blob/master/docs/specifications/tests/TestMessages.md

**Comment by pawal** [comment]
You can update that page with one of the scripts I wrote:
https://github.com/dotse/zonemaster/blob/master/utils/maptestmessages.pl

**Comment by matsduf** [comment]
F2F: Close.
