### ISSUE TITLE
Restrict copyright notices to just the LICENSE file

### ISSUE THREAD

**Issue by JohanIIS** [zonemaster/zonemaster#574]
Currently, most files have a copyright footer that requires yearly updates which don't always happen. Some older files haven't had their footer updated since 2013.

Since we do use a LICENSE file and do have a documentation copyright section within it, I propose we keep that as our only copyright notice and remove the footer from all other files. Updating a large amount of files separately seems unnecessary when we have a general file that serves the same purpose.

**Comment by pawal** [comment]
Keeping the copyright notice in each source code file accomplishes two things:

 * Your copyright is asserted no matter how your code disintegrates and scatters in the future.
 * You make the terms of using, distributing and modifying it quite clear, even if someone happened to receive only a small part of a library that you wrote.

If ever you actually need to enforce your license, it is critical that the other party can't say that the terms were ambiguous or missing.

**Comment by matsduf** [comment]
@sandoche2k, what do you think? We could discuss at the F2F, and prepare by checking with layers at IIS and Afnic, respectively.

**Comment by sandoche2k** [comment]
I agree with @JohanIIS about the maintenance part. @pawal other open source examples seems to do as @JohanIIS proposes (https://github.com/hubotio/hubot/blob/master/LICENSE.md). And that way seems to appropriate -> https://help.github.com/articles/licensing-a-repository/

**Comment by sandoche2k** [comment]
@JohanIIS will create a License file for every repo.

**Comment by sandoche2k** [comment]
@JohanIIS we need this issue to be fixed for this release. Please have a look

**Comment by sandoche2k** [comment]
@JohanIIS would you have time to resolve this issue for this release?

**Comment by sandoche2k** [comment]
@JohanIIS @matsduf License file should be updated and Copyright should be removed copyright footer from other files.

**Comment by sandoche2k** [comment]
@matsduf can we close this issue for 2019.1?

**Comment by sandoche2k** [comment]
@matsduf close?

**Comment by matsduf** [comment]
We think that we have updated in all files. If not, we can create a new issue.
