### ISSUE TITLE
Inconsistency in consistency03

### ISSUE THREAD

**Issue by mattias-p** [zonemaster/zonemaster#587]
In [CONSISTENCY03](https://github.com/dotse/zonemaster/blob/8d26e63c150979b48fd09bf044aec686f400996e/docs/specifications/tests/Consistency-TP/consistency03.md) the Objective section describes the consistency requirements for the REFRESH, RETRY, EXPIRE and MINIMUM fields. The Steps section compares the RNAME field. The Objective and Steps sections must agree.

**Comment by sandoche2k** [comment]
@mattias-p close?

**Comment by mattias-p** [comment]
The Objective and Steps sections are in agreement now.
