### ISSUE TITLE
Simplify ASN lookup instructions

### ISSUE THREAD

**Issue by mattias-p** [zonemaster/zonemaster#628]
The ASN lookup instructions introduced in #597 are too detailed. Instead of taking the responsibility to explain many of the intricacies, the instructions should defer as much as possible to the ASN database provider documentation.

**Comment by matsduf** [comment]
I cannot see what we would win of make the specification less explicit. By having an explicit specification we decrease the risk that the implementation will differ from the specification. In the updates of other test cases, e.g. #620, we have made the specification more explicit.

**Comment by mattias-p** [comment]
This is an issue of keeping things in their right places.

It is not the responsibility of the Zonemaster project to specify how DNS packets are represented. We rely on other specifications for that. On the other hand it is our responsibility to specify Consistency05, because Consistency05 is ours.

Likewise, neither is it the responsibility of the Zonemaster project to specify how ASN database requests are represented. If existing ASN database protocol specifications aren't clear enough for our purposes, we should talk to the maintainers of those documents.

**Comment by matsduf** [comment]
This issue refers to a PR that was closed and not merged (#597). This issue is probably not relevant anymore.
