### ISSUE TITLE
Report.md cannot be correctly generated

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster#657]
The document docs/specifications/tests/[Report.md] is created from the directory docs/specifications/[tests] with the following command:

```
make map
```

It cannot be correctly created when the Test Case specification is in the updated format.

Expected extract:

|Req|Requirement desription|Level     |Test Case ID|Test Description|
|:--|:---------------------|:---------|:-----------|:---------------|
|R08|The child domain has atleast one working name server|[  Basic-TP](Basic-TP/README.md)|[BASIC02](./Basic-TP/basic02.md)|  The domain must have at least one working name server|

Actual extract:

|Req|Requirement desription|Level     |Test Case ID|Test Description|
|:--|:---------------------|:---------|:-----------|:---------------|
|R08|The child domain has atleast one working name server|[  Basic-TP](Basic-TP/README.md)|[missing](./Basic-TP/basic02.md)|          missing|

No error message is generated.

[Report.md]: https://github.com/zonemaster/zonemaster/blob/master/docs/specifications/tests/Report.md
[tests]: https://github.com/zonemaster/zonemaster/tree/master/docs/specifications/tests

**Comment by sandoche2k** [comment]
@matsduf close?

**Comment by sandoche2k** [comment]
@matsduf any updates?

**Comment by matsduf** [comment]
The document is removed by #881.
