### ISSUE TITLE
Style: Capitalization of variable names in specifications

### ISSUE THREAD

**Issue by mattias-p** [zonemaster/zonemaster#665]
The style guide should have an entry regarding the capitalization of variable names in specifications.

Today it seems most common that every word is capitalized (e.g. "Domain Part"), but sometimes only the first word is capitalized (e.g. "Mail address"). I think we should be consistent on this point.

**Comment by matsduf** [comment]
From my point of view it has been a mistake not to have initial capital letter on all words, i.e. "Mail Address" is what I would prefer.

**Comment by mattias-p** [comment]
(Accidentally pushed the close button.)

**Comment by matsduf** [comment]
@mattias-p to create a PR to docs/internal-documentation/maintenance/StyleGuide.md
