### ISSUE TITLE
Split message BROKEN_EDNS_SUPPORT in Nameserver02

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster#672]
There are three different sub-cases in [Nameserver02] that are tagged with BROKEN_EDNS_SUPPORT, which prevents us from writing good messages for the users to be able to differentiate. That should be updated.

See #749.
 
[Nameserver02]: https://github.com/zonemaster/zonemaster/blob/master/docs/specifications/tests/Nameserver-TP/nameserver02.md

**Comment by sandoche2k** [comment]
@matsduf @vlevigneron can this be closed?

**Comment by sandoche2k** [comment]
We need modification in specification. @matsduf will have a look and update

**Comment by vlevigneron** [comment]
@matsduf do you plan to create a new issue in the Engine once this one has been merged or can I reference this one in the patch I have to do in the Engine ?

**Comment by matsduf** [comment]
Solved by #749.
