### ISSUE TITLE
Supported environment Zonemaster-GUI

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster#675]
The README in this repository should refer to web browsers and underlying OSes when listing supported environment for Zonemaster-GUI. Also see zonemaster/zonemaster-gui#26.

**Comment by sandoche2k** [comment]
@pamasse add that to GUI readme and provide a link from ZM readme.

**Comment by sandoche2k** [comment]
@pamasse any updates?

**Comment by sandoche2k** [comment]
Done in the PR https://github.com/zonemaster/zonemaster/pull/756

**Comment by sandoche2k** [comment]
@matsduf close?

**Comment by matsduf** [comment]
Resolved by #756.
