### ISSUE TITLE
DNSSSEC results disappeared from the zonemaster tests

### ISSUE THREAD

**Issue by sandoche2k** [zonemaster/zonemaster#753]
https://zonemaster.net/result/24bda7791431e976

I do not see the DNSSEC tests in the result

Same test with https://zonemaster.iis.se/?resultid=8b4037efc3192fb4 shows DNSSEC results

With the CLI from the zonemaster.net server

```

zonemaster-cli --test DNSSEC unknownalgorithm.ok.ok.bad-dnssec.wb.sidnlabs.nl
Durée   Niveau    Message
======= ========= =======
Le résultat semble concluant.
```

**Comment by sandoche2k** [comment]
Refer to https://github.com/zonemaster/zonemaster-engine/issues/521 and close this issue

**Comment by matsduf** [comment]
Bug in Zonemaster-Engine. Close here.
