### ISSUE TITLE
Add test for Null MX records (RFC 7505)

### ISSUE THREAD

**Issue by sandoche2k** [zonemaster/zonemaster#754]

**Comment by matsduf** [comment]
Test Case [Zone09] ("MX record present") verifies that the domain has SMTP target (MX or address). I see no point is testing for Null MX record as such, but we should make sure that [Zone09] accepts a Null MX, and maybe outputting a special INFO message that the domain has a Null MX.

[Zone09]: https://github.com/zonemaster/zonemaster/blob/master/docs/specifications/tests/Zone-TP/zone09.md

**Comment by matsduf** [comment]
@sandoche2k, while updating Zone09 I wonder what we should expect from Null MX? More than not expecting any mail target?

**Comment by matsduf** [comment]
Updated Zone09 considers "Null MX" (see PR #870).

**Comment by matsduf** [comment]
Resolved by #870, and inplemted in https://github.com/zonemaster/zonemaster-engine/pull/1109
