### ISSUE TITLE
Introductory material

### ISSUE THREAD

**Issue by mattias-p** [zonemaster/zonemaster#757]
We should have an introduction to DNS that gives our users a minimal theoretical framework to help them understand the emitted messages. It should assume that the reader has knows what DNS is and what a domain is. It should provide explanations for what a zone is, what a delegation is and how name servers are represented as NS records.

**Comment by sandoche2k** [comment]
@mattias-p are you planning to do this for 2019.1? Where do you want to provide this introduction? DNS is a complex subject and providing appropriate information vary according to the user. Providing complete information for all types of users is a herculean task. I am not sure we need to do this? If yes, who will it get assigned to? @matsduf for comments.

**Comment by matsduf** [comment]
I do not think this could be done for v2019.1.

We have a problem that the messages are too short to be comprehensible. We also have a problem that the context of the messages is imprecise, i.e. not pointing to the test case that outputs it. In DNScheck you could expand the message to a longer text. I would like to see that.

**Comment by matsduf** [comment]
F2F: Won't fix within our time frame.

**Comment by mattias-p** [comment]
The reasoning here is that we focus on more advanced users for the time being.
