### ISSUE TITLE
Update DNSESEC01 on legal values

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster#762]
When [draft-ietf-dnsop-algorithm-update] has been accepted as RFC then [DNSSEC01] specification must be updated.

Also see https://indico.dns-oarc.net/event/31/contributions/688/attachments/650/1067/matthijs-mekking-oarc30-unsupported-algorithms.pdf

[draft-ietf-dnsop-algorithm-update]: https://datatracker.ietf.org/doc/draft-ietf-dnsop-algorithm-update/?include_text=1

[DNSSEC01]: https://github.com/zonemaster/zonemaster/blob/master/docs/specifications/tests/DNSSEC-TP/dnssec01.md

**Comment by matsduf** [comment]
The created PR must not be merged before the RFC is ready.

**Comment by pawal** [comment]
I don't see any reason at all to update the DNSSEC01 specification.

**Comment by matsduf** [comment]
The specification needs update and rewriting. Cf. with e.g. DNSSEC05.

**Comment by sandoche2k** [comment]
Should we follow the RFC or the IANA registry? If there is a new RFC the IANA registry will be updated isn't it?

**Comment by matsduf** [comment]
The RFC is out, so right now the RFC is stricter. See my update of DNSSEC05, which is in the same situation, in PR #777.

**Comment by sandoche2k** [comment]
I completely agree with you that the RFC is the reference document. But, here we are discussing about algorithms that are currently in use could be deprecated and new algorithms that could be added. As I understand, the IANA registry will be updated but the RFC will be outdated. That is the reason i am posing the question.

**Comment by matsduf** [comment]
A PR to solve this has been created as #770.

**Comment by matsduf** [comment]
Solved by #779.
