### ISSUE TITLE
Update DNSESEC05 on legal values

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster#763]
When [draft-ietf-dnsop-algorithm-update] has been accepted as RFC then [DNSSEC05] specification must be updated.

Also see https://indico.dns-oarc.net/event/31/contributions/688/attachments/650/1067/matthijs-mekking-oarc30-unsupported-algorithms.pdf

[draft-ietf-dnsop-algorithm-update]: https://datatracker.ietf.org/doc/draft-ietf-dnsop-algorithm-update/?include_text=1

[DNSSEC05]: https://github.com/zonemaster/zonemaster/blob/master/docs/specifications/tests/DNSSEC-TP/dnssec05.md

Solution in #777.

**Comment by matsduf** [comment]
The created PR must not be merged before the RFC is ready.

**Comment by pawal** [comment]
I don't see any reason at all to update DNSSEC05, the specification already refers to the IANA registry of DNSSEC Algorithm Numbers - and this registry is being affected by the acceptance of the mentioned draft.

**Comment by matsduf** [comment]
@pawal, if you take a look at the specification you will see why it must be updated.

https://github.com/zonemaster/zonemaster/blob/master/docs/specifications/tests/DNSSEC-TP/dnssec05.md

**Comment by sandoche2k** [comment]
Should we follow the RFC or the IANA registry? If there is a new RFC the IANA registry will be updated isn't it?

**Comment by matsduf** [comment]
Resolved by #777.
