### ISSUE TITLE
Out-dated documentation on checking and updating version numbers

### ISSUE THREAD

**Issue by mattias-p** [zonemaster/zonemaster#771]
Today we have documentation in two places on where version numbers defined:
* https://github.com/zonemaster/zonemaster/blob/master/docs/internal-documentation/maintenance/ReleaseProcess.md#3-set-all-version-numbers
* https://github.com/zonemaster/zonemaster/blob/master/docs/design/Versions%20and%20Releases.md#introduction

The first one is up to date but the second one is not. This information should on be spelled out in one place only. If needed there should be a link from the other place.

**Comment by matsduf** [comment]
A PR is created in #789.

It is not that the definition of version number was outdated, as far as I could see. What is outdated in [Versions and Releases] is where version number is set. In the version in the PR that has been removed. 

[Versions and Releases]: https://github.com/zonemaster/zonemaster/blob/master/docs/design/Versions%20and%20Releases.md

**Comment by matsduf** [comment]
Resolved by #789.
