### ISSUE TITLE
test for private IP addresses in NS records

### ISSUE THREAD

**Issue by donestefan** [zonemaster/zonemaster#790]
Referencing rfc1918 private IP addresses in NS records often causes trouble during dns resolution. It is not necessarily an error and might be intentional - but mostly it is clear sign of misconfiguration. Could you add a test that issues a "notice" when such an IP address is used in a delegation/ns-record?
I might help debugging dns split-view configurations where dns resolution works in intranet - but not externally (internet)

**Comment by matsduf** [comment]
@donestefan, do you have an example on a domain name that is delegated to a name server with a private IPv4 address? Zonemaster should capture that, see Test Case [Address01]. You should get the message NAMESERVER_IP_PRIVATE_NETWORK ("Nameserver {ns} has an IP address ({address}) with prefix {prefix} referenced in RFC1918 as a 'Private-Use'").

If you do not see that message, please give me some more details, if possible.

[Address01]: https://github.com/zonemaster/zonemaster/blob/master/docs/specifications/tests/Address-TP/address01.md

**Comment by donestefan** [comment]
You can have a look at https://zonemaster.net/result/a1fd654e2c01ff58.
It only shows `Nameserver did not respond to NS query`. 
Thinking of it - I guess there should be a lot more warnings. Apart from the private IP-address I'd also expect a note about a the missing second nameserver.

Maybe something is preventing additional tests from being executed?

**Comment by matsduf** [comment]
In this case, Zonemaster only executes the [Basic] tests. If [Basic02] fails, Zonemaster does not continue, and therefore never reaches [Address01] where privat address would be noticed. Yes, other tests are also not executed.

If the domain has a second name server on public  address the private address should be noticed. With only one name server and that not being reachable, there is not much that Zonemaster could do.

[Basic]: https://github.com/zonemaster/zonemaster/blob/master/docs/specifications/tests/Basic-TP/README.md
[Basic02]: https://github.com/zonemaster/zonemaster/blob/master/docs/specifications/tests/Basic-TP/basic02.md
[Address01]: https://github.com/zonemaster/zonemaster/blob/master/docs/specifications/tests/Address-TP/address01.md

**Comment by donestefan** [comment]
Thanks for the clarification. I expected that zonemaster would do all the tests 
1) on the name servers of the parent domain and 
2) on the name servers of the actual child domain and 
3) compares the results (should be equal).

I understand that zonemaster can not execute step 2 and 3. But in my example I don't see a reason it 
does not execute the Address01 test (and probably others) with the information available on the parent domain servers. Am I missing something?

**Comment by matsduf** [comment]
You are correct that it would be possible to verify that the IP addresses in the delegation, or from a lookup of the name server names in the delegation, are globally routable. In the beginning of the project it was decided no tests beyond "basic" are executed unless there is at least one name server that replies for the zone of the domain in testing.

The message that you get in https://zonemaster.net/result/a1fd654e2c01ff58 is not very clear, so moving [Address01] to [Basic] might be a good idea. That could give information on why the name server or servers are not reachable.

[Basic]: https://github.com/zonemaster/zonemaster/blob/master/docs/specifications/tests/Basic-TP/README.md
[Address01]: https://github.com/zonemaster/zonemaster/blob/master/docs/specifications/tests/Address-TP/address01.md

**Comment by matsduf** [comment]
This issue can be closed. A proposal to move Address01 is found in #791.
