### ISSUE TITLE
Consider moving Address01 to Basic

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster#791]
If all NS in delegation points IP addresses not globally routable (e.g. private IPv4 addresses) then Zonemaster does not go beyond [Basic] and Zonemaster will never discover that the addresses are not reachable since that is tested in [Address01].

Should Address01 be moved to Basic instead to be able to capture the problem with a description in such a case?

This relates to the issue described in #790.

[Basic]: https://github.com/zonemaster/zonemaster/blob/master/docs/specifications/tests/Basic-TP/README.md
[Address01]: https://github.com/zonemaster/zonemaster/blob/master/docs/specifications/tests/Address-TP/address01.md

**Comment by pawal** [comment]
I think there are strong use-cases for testing internal DNS-setups. So this is a reason for not moving this to the BASIC-tests, since this will interrupt further testing. In other words, I think it should be possible to test zones with RFC1918 addresses.

Unreachable addresses will happen irregardless of being in the RFC1918 space or not.

**Comment by matsduf** [comment]
@pawal, I think you missunderstand the proposal. Zonemaster terminates unless [Basic02] passes. In the case that all name servers are unreachable because they are running on private addresses and we are testing from the outside it will not be reported that the IP addresses in fact are private.

Nothing is changed for your use case. The idea is not to stop just because the addresses are private, just to be able to report it. I would stipp be the outcome of [Basic02] that determines if Zonemaster would go beyond Basic or not.

[Basic02]: https://github.com/zonemaster/zonemaster/blob/master/docs/specifications/tests/Basic-TP/basic02.md

**Comment by donestefan** [comment]
One could argue that most tests using [Method 1 ](https://github.com/zonemaster/zonemaster/blob/master/docs/specifications/tests/Methods.md#method-1-obtain-the-parent-domain)and/or [Method 2](https://github.com/zonemaster/zonemaster/blob/master/docs/specifications/tests/Methods.md#method-2-obtain-glue-name-records-from-parent) and/or [Method 4](https://github.com/zonemaster/zonemaster/blob/master/docs/specifications/tests/Methods.md#method-4-obtain-glue-address-records-from-parent) can continue if [Basic02](https://github.com/zonemaster/zonemaster/blob/master/docs/specifications/tests/Basic-TP/basic02.md#basic02-the-domain-must-have-at-least-one-working-name-server) fails.
Maybe not the "Consistency-TP" checks. But certainly all the "Address-TP" checks and probably quite a few others.

**Comment by matsduf** [comment]
@donestefan, thank you for your input. Not being able to reach the zone at all (which failing [Basic02] means) is fundamental. Understanding why (which [Address01] could explain) is essential. Other details that could be discovered without being able to reach the zone are probably less urgent.

Your suggestion will be considered. 

[Address01]: https://github.com/zonemaster/zonemaster/blob/master/docs/specifications/tests/Address-TP/address01.md
[Basic02]: https://github.com/zonemaster/zonemaster/blob/master/docs/specifications/tests/Basic-TP/basic02.md

**Comment by matsduf** [comment]
OK from F2F. @matsduf will create proposal.

**Comment by matsduf** [comment]
The gain of doing the change is too little. Updated Basic02 will give better messages relevant for this issue (#1085).
