### ISSUE TITLE
Do TestRequirements fill any function anymore?

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster#795]
Among the documents we have [TestRequirements] with listed and numbered requirements separated from the [test cases]. The requirement list was an important input when Zonemaster was created as an input to what test cases to create. Today we do not start by updating [TestRequirements], rather we have an issue pointing out something that should be tested, and then we create the test case. And finally we try to find something to write in [TestRequirements].

~~I suggest that we move [TestRequirements] to the history and instead have the test cases as the starting point.~~

*Updated:* Update the [TestRequirements] and remove references to legacy tools.

I suggest that we create one directory file of all test cases and put that above all test case folders. The README.md in the test case folders are instead static files that points to the new directory file.

All our files are markdown files (.md) and we have scripts that try to use the files as database, which does not work very well. Let us simplify all this by only updating the test case documents and the new directory file.

- [x] Create test case directory file based on existing test cases.
- [x] Update the test case folder README files to the new directory file.
- [x] Create a concatenated README of all test cases at top level.
- [x] Review each requirement and determine if that requirement statement is included in the purpose section of the relevent test case, and if not work it in if possible.
- [x] Remove references to the TestRequirements in README files.
- [x] ~~Move the TestRequirements to the history.~~ Update TestRequirements
- [x] Remove unneeded scripts.

*Updated*: PR #881 resolves this issue.

If this is done #657 can be closed.

[test cases]: https://github.com/zonemaster/zonemaster/tree/master/docs/specifications/tests
[TestRequirements]: https://github.com/zonemaster/zonemaster/blob/master/docs/requirements/TestRequirements.md

**Comment by pawal** [comment]
If you still want to follow IEEE 829-2008 for creating a test plan, you want to keep an updated list of requirements for the tests.

**Comment by matsduf** [comment]
That standard is "superseded" by IEEE, and it is not an open standard. I see no strong value to try to follow a standard that few people know the details of.

**Comment by matsduf** [comment]
Issue description updated at F2F and agreed to proceed.

**Comment by matsduf** [comment]
Resolved by #881
