### ISSUE TITLE
RFC8080 Support

### ISSUE THREAD

**Issue by andreasschulze** [zonemaster/zonemaster#796]
just a friendly reminder:

currently (08/2019) zonemaster.net could not handle ed25519 keys.
such keys are reported as "Unknown cryptographic algorithm"

example: https://zonemaster.net/result/573794bafe9988b1

**Comment by mattias-p** [comment]
Thanks for showing interest! It can make a difference when we prioritize what to work on.

Closing this as a duplicate of zonemaster/zonemaster-engine#564.
