### ISSUE TITLE
using zonemaster-cli in a isolated network

### ISSUE THREAD

**Issue by andreasschulze** [zonemaster/zonemaster#798]
I build zonemaster-cli as docker container. Now I could check zones running the container on my own server :-)

But the intended use is a closed, isolated network without public internet access.
zonemaster-cli still insist on talking to [a-m].root-servers.net. which are unreachable there.

even if I use `zonemaster-cli example.test. --ns 192.0.2.52`

Is this use-case impossible by design?

**Comment by matsduf** [comment]
The primary use-case is to test delegated domain names in the public domain name tree. The second use-case, to test undelegated domain names, are meant for domain names to be delegated in the public tree. Your use case is of course valid, but at the design is has not been a requirement that it should be possible to run such a test, and the implementation obviously does not permit it.

To have a private root you have to patch Zonemaster replacing the built-in root name servers, but after that it works in a private setting. So if you are willing to patch and have a private root, your use-case will work.

**Comment by sandoche2k** [comment]
@matsduf can we close this issue?

**Comment by matsduf** [comment]
Out of scope.
