### ISSUE TITLE
Ed25519 not supported?

### ISSUE THREAD

**Issue by gkroon** [zonemaster/zonemaster#799]
I noticed that when using https://www.zonemaster.net/domain_check, I couldn't validate my zones that use Ed25519 keys. Please verify this by testing **ed25519.nl**.

**Comment by matsduf** [comment]
Thank you for reporting this problem/bug. We have issues zonemaster/zonemaster-ldns#51 and zonemaster/zonemaster-ldns#84 that cover the the problem. It must be solved in [zonemaster/zonemaster-ldns].

[zonemaster/zonemaster-ldns]: https://github.com/zonemaster/zonemaster-ldns
