### ISSUE TITLE
is the "preserve case test" right?

### ISSUE THREAD

**Issue by andreasschulze** [zonemaster/zonemaster#845]
I found in https://zonemaster.net/result/78a0bd30af689fc7 a test-result:
Nameserver ns11.jimdo.com/162.159.24.115 preserves original case of queried names (wwW.DP-sTEuer.de).

but manual test looks different to me:

$ kdig @ns11.jimdo.com. wwW.DP-sTEuer.de. +norec +nocomment +nostats +noheader 
;;www.dp-steuer.de.             IN      A
www.dp-steuer.de.       3600    IN      CNAME   web.jimdosite.com.

the nameserver **DO NOT** preserve original case.

Is this a Bug because the CNAME answer trigger a second querie with all lower case which then is answered with all lowercase?

**Comment by matsduf** [comment]
What are compared is the query name sent in the Question section of the query and of the response, respectively. In both cases we should look at the Question section. In your example we do not see the Question section of the response. See [Nameserver08]. The case in the response can rather match the case in the zone file.

When I check against the same name server, not only is the case preserved in the Question section (relevant for the test case), but also in the Answer has the same case mix (but not relevant for the test case).

```
; <<>> DiG 9.10.6 <<>> @ns11.jimdo.com. wwW.DP-sTEuer.de. +norec +noedns
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 22790
;; flags: qr aa; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;wwW.DP-sTEuer.de.		IN	A

;; ANSWER SECTION:
wwW.DP-sTEuer.de.	3600	IN	CNAME	web.jimdosite.com.

;; Query time: 45 msec
;; SERVER: 162.159.24.115#53(162.159.24.115)
;; WHEN: Mon Apr 27 20:09:49 CEST 2020
;; MSG SIZE  rcvd: 65
```

[Nameserver08]: https://github.com/zonemaster/zonemaster/blob/develop/docs/specifications/tests/Nameserver-TP/nameserver08.md
