### ISSUE TITLE
feature request to add named-checkzone

### ISSUE THREAD

**Issue by marckranat** [zonemaster/zonemaster#857]
It's a big ask I know, and would require uploading/pasting a zone file into a form, but adding named-checkzone as part of this suite would complete it for me.

**Comment by sandoche2k** [comment]
We will discuss this feature and get back to you in a week.

**Comment by matsduf** [comment]
@marckranat, can you elaborate your idea?

`named-checkzone` is part of the Bind program and is for checking the zone as such without considering the servers.

The purpose of Zonemaster is to be able to check a "running" zone.

**Comment by marckranat** [comment]
@matsduf maybe it's just me, but I often have to deal with zonefiles which just won't load in bind which I might not have access to, the only way to check them is from the actual zonefile.
As far as I know there is no online test for this available.
But yes I see your distinction, and you cover so much ground with your tests already, but for me it would be pretty useful.

**Comment by matsduf** [comment]
@marckranat, checking zonefile is of course crucial for finding problem, but it very different from Zonemaster which checks the zone on running name servers. As we see it, there would be little code in common between what Zonemaster is today and what would be required for your idea. Our resources are limited and we cannot expand the scope of our project.

I'm, we have to say "no" to your proposal.
