### ISSUE TITLE
Inconsistent messages about the number of name servers

### ISSUE THREAD

**Issue by bortzmeyer** [zonemaster/zonemaster#886]
The domain transemigrate.org has a discrepancy of its NS set between the parent and the zone, and also zone auth. servers reply strangely to SOA and NS requests.

As a result, Zonemaster displays two inconsistent messages:

DELEGATION | ERROR | Child does not list enough (0) nameservers (). Lower limit set to 2.
-- | -- | --
DELEGATION | INFO | Child  lists enough (4) nameservers (pns101.cloudns.net; pns102.cloudns.net;  pns103.cloudns.net; pns104.cloudns.net) that resolve to IPv4 addresses  (185.136.96.99; 185.136.97.99; 185.136.98.99; 185.136.99.99). Lower  limit set to 2.

So, enough name servers or not?

**Comment by matsduf** [comment]
@bortzmeyer, when I test now I cannot see the ERROR message when I ran a test in zonemaster.net (https://www.zonemaster.net/result/ea205c8bcc24a142). The zone looks fine, besides for not being signed. I guess the zone has been updated.

It does look like a bug in Zonemaster, and if you see it again, please tell us. Thanks.
