### ISSUE TITLE
Unable to get Terminal Size

### ISSUE THREAD

**Issue by andreasschulze** [zonemaster/zonemaster#934]
using the github/HEAD version I saw the following failure:

```
Unable to get Terminal Size. The TIOCGWINSZ ioctl didn't work. The COLUMNS and LINES environment variables didn't work. The resize program didn't work. The stty program didn't work. at /usr/local/share/perl/5.32.1/Getopt/Long/Descriptive.pm line 295.
Use of uninitialized value $Getopt::Long::Descriptive::TERM_WIDTH in subtraction (-) at /usr/local/share/perl/5.32.1/Getopt/Long/Descriptive/Usage.pm line 163.
<last warning repeat ~50 times>
```

```
$ zonemaster --version
CLI version:    v3.0.4
Engine version: v4.1.0

Test module versions:
        Address: v1.0.8
        Basic: v1.0.15
        Connectivity: v1.0.17
        Consistency: v1.1.16
        DNSSEC: v1.1.33
        Delegation: v1.0.20
        Nameserver: v1.0.26
        Syntax: v1.0.10
        Zone: v1.0.14
```

**Comment by matsduf** [comment]
Can you please describe what you did to the the error? Did you install following the installation instructions, starting with https://github.com/zonemaster/zonemaster-engine/blob/master/docs/Installation.md?

**Comment by andreasschulze** [comment]
I reread the instructions and found I missed two packages `libemail-valid-perl` and `libmoosex-singleton-perl`. See also https://github.com/zonemaster/zonemaster-engine/commit/68fbcf59b2b58b2fe54f209018e57839bc2def0f#diff-fcf6d384bb8308546cecce54bb9678c715f95c119b402f9b61a78e0cf3d8fbc4R54

Rebuild my container and all is working **silent** again. This Ticket could be closed. Thanks.

**Comment by matsduf** [comment]
@andreasschulze, thanks. If you have any comments on the installation instructions that can make them better, please create an issue on that.
