### ISSUE TITLE
No more travis integration since June 15th

### ISSUE THREAD

**Issue by blacksponge** [zonemaster/zonemaster#967]
TravisCI has moved from travis-ci.org to travis-ci.com and stopped services on travis-ci.org on June 15th.

From their website:
>  Since June 15th, 2021, the building on travis-ci.org is ceased. Please use travis-ci.com from now on.

We should make the switch asap.

**Comment by matsduf** [comment]
I have updated zonemaster-gui. I will create a PR to see if it works.

**Comment by matsduf** [comment]
@blacksponge, can you include the link or more information?

**Comment by blacksponge** [comment]
I don't have much info beside what the banner on https://travis-ci.org/ says.

**Comment by pnax** [comment]
They have written a blog entry about it : https://blog.travis-ci.com/2021-05-07-orgshutdown

**Comment by matsduf** [comment]
It should be working now.

**Comment by matsduf** [comment]
@blacksponge and @pnax, please create a test PR to verify that it works even for you. See my test PR that I created after activation: https://github.com/zonemaster/zonemaster-backend/pull/792

**Comment by blacksponge** [comment]
It seems to work for me, thanks

**Comment by matsduf** [comment]
OK, then I close again.
