### ISSUE TITLE
What modern RFC recommends SOA values for today

### ISSUE THREAD

**Issue by Ressy66** [zonemaster/zonemaster#972]
zonemaster seems to"recommend" different SOA values then rfc1912, example, values that used to be 3 hours now claims recommendation of 4 hours, So I'm seeking the RFC that seems to have superseded 1912, (like values used in your old zonecheck)

**Comment by Ressy66** [comment]
Also, when issuing notices or warnings or failures and stating why your doing so, the old zoncheck used to reference the RFC and section so users know that the warnings are genuine and not some figured pulled out of a hat , could we get this in a future update please/

**Comment by matsduf** [comment]
Thank you for bringing this up.

The motivations behind the tests, and references to RFCs and similar documents, are found in the test case specifications. You will find a list with links to all test cases in https://github.com/zonemaster/zonemaster/tree/master/docs/specifications/tests#list-of-defined-test-cases.

Specifically, test cases zone02-06 cover the SOA values.

Do the specification fulfill your requirement of motivation behind the messages?

**Comment by Ressy66** [comment]
OK, so the values are RIPE recommends from 1999, not values from any RFC which for example makes it legal and recommend 2-12hrs for refresh, so for all the years  everyones being using 3 hours is is acceptable, but you chose to determin 4 hours minimum, making people who use 3hours think  they are wrong, when they clearly are not, when there is no more current RFC superseding 1912.

You also make retry min 1hr when the old 20 mins is still very valid.

I congratulate the team on zonemaster, it's nicer than zonecheck, but seriously  if you want to be a"are you good dns health" you should use correct values, and I suggest those ripe chosen values ne foxed to RFC values.

**Comment by Ressy66** [comment]
in interim where do we change these values?
only place I can find is in cpan/build/Zonemaster-LDNS-2.2.0-1/t/rr.t   which makes no difference...

**Comment by Ressy66** [comment]
/usr/local/share/perl5/Zonemaster/Engine/Constants.pm
is location to edit these values to correct to RFC values...  of course will be wiped out on update if its not fixed upstream.

(this browser wont work properly with guthub, it has never let me see the edit option, just the ever spinning wheel syndrome)

**Comment by matsduf** [comment]
I agree that those test cases need review and probably updates when it comes to limits and severity level of messages. I have created issue #974 for that. When the test cases are updated, the implementation can be updated. I will close this issue, but the updates that you request will be handled through the new issue created.

**Comment by matsduf** [comment]
@Ressy66, I have created an issue, zonemaster/zonemaster-engine#945, to move those SOA values from Constants.pm to the profile, which is the place for the user to adapt Zonemaster to its needs.

**Comment by Ressy66** [comment]
excellent, thanks
