### ISSUE TITLE
Cosmetic working

### ISSUE THREAD

**Issue by Ressy66** [zonemaster/zonemaster#990]
10	ZONE	INFO	Target (MX=foo/MX=foo) found to deliver e-mail for the domain name.

target found to deliver e-mail, says zonemaster tests this by sending commands to the domains MX server to test delivery.
Although this would be awesome, this is not the case, checked by observing my own mail servers and wireshark.

So either, zonemaster needs to do such a test, or, the wording needs to be changed so people do not think its actually tested a mail server.

**Comment by matsduf** [comment]
Thank you for pointing this out.

Zonemaster does not and will not try to connect to mail servers. Older DNS validation programs did that, and it was not a good idea.

I agree that the wording is not good. We will update that.

**Comment by matsduf** [comment]
Issue is created in https://github.com/zonemaster/zonemaster-engine/issues/967

**Comment by matsduf** [comment]
A pull request has been created and the correction will be included in the next release, zonemaster/zonemaster-engine#968

**Comment by matsduf** [comment]
Issue resolved by zonemaster/zonemaster-engine#968
